name: Flake Check

on: 
  workflow_run:
    workflows: ["Flake Update"]
    types:
      - completed

jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Flake update
      run: nix flake check --all-systems
