name: Python Tests

on: 
  workflow_run:
    workflows: ["Flake Check"]
    types:
      - completed

jobs:
  pytest:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Poetry install
      run: |
        nix-shell -p poetry --run "poetry install"
       
    - name: Run tests
      run: |
        nix-shell -p poetry --run "poetry run pytest"
