name: Python Tests

on: 
  workflow_run:
    workflows: ["Flake Update"]
    types:
      - completed

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Flake update
      run: nix develop

    - name: Run tests
      run: poetry run pytest
